PlanoramaEvents/planorama

README.md

The latest development branch won't run without these new environment variables described in the README file

Added instructions for new mandatory variables for the .envrc file

---

app/javascript/constants/strings.js
app/javascript/surveys/edit-survey-question.vue
app/javascript/surveys/question.mixin.js

When you actually select the question, the box appears to move a tiny bit, but it's much better than the double box I had earlier

Put a box around the survey question text when editing a question

---

app/javascript/people/person_tabs.vue
app/javascript/sessions/session_tabs.vue

- people edit back button always goes to people list, regardless of how you got there
- sessions edit back button always goes to sessions list, regardless of how you got there

PLAN-314 back buttons do different things

---

app/javascript/people/person_tabs.vue

- only people who can see the admin page can see the admin tab.
(not that there is anything on it yet)

PLAN-310 hide admin tab like in the flyout

---

app/javascript/profile/person_demographics.vue
app/javascript/profile/person_details.vue

- you can see and edit your own restricted data
- you cannot see and edit the restricted data of others unless you are an admin
- in the future, this should use the sensitive data permission bit instead of admin perms

PLAN-324 disallow editing sensitive data

---

app/javascript/packs/application.js
config/webpack/environment.js

does not force the page to reload on a 422, instead just displays the nicely
formatted error message.
as a bonus - now NEVER displays the stupid popup in dev, only in production envs. PHEW

PLAN-321 fix 422 error handling

---

app/javascript/schedule/schedule_day.vue

Do not remove the shown conflict when selecting another session
(Note: conflict will still change or disappear on dragging a session onto grid or changing time as that was the original spec)

keep conflict when selecting another session

---

app/javascript/components/date_time.mixin.js
app/javascript/conflicts/session_conflicts.vue
app/javascript/constants/strings.js
app/javascript/mixins.js
app/javascript/schedule/schedule_screen.vue
app/javascript/sessions/assign_participants.vue
app/javascript/sessions/session_fields.mixin.js
app/javascript/sessions/session_sidebar.vue
app/javascript/sessions/session_summary.vue
app/javascript/sessions/session_table.vue
app/javascript/sessions/session_tabs.vue
app/javascript/sessions/view_participant_type.vue
app/javascript/sessions/view_participants.vue
app/javascript/shared/convention-timezone.mixin.js
app/javascript/stylesheets/style.scss

- fix participant assignment console errors
- area, format, invisible participants, interest instructions, scheduled,
proofed, schedule tab on flyout
- move open for interest into top section of flyout
- consolidate session field formatting methods
- add conflicts tab to session flyout
- remove the session date/time in the session tabs
- change the spacing/borders around multiple conflicts

PLAN-315 PLAN-316 PLAN-287 add fields to session flyout

---

app/javascript/surveys/edit-survey-controls.vue
app/javascript/surveys/survey.mixin.js

If there is no page and no question selected:
- add page adds a page to the bottom
- add question/hr/text adds a question to the bottom of the last page
If there is a page but no question selected:
- add page adds a page after the current page, and all the questions on the current page should move to the new page
- add question/hr/text adds a question as the first question on the selected page
If there is a question but no page selected:
- select the question's page as the page
If there is both a question and a page selected:
- add page adds a page after the currently selected question, taking all the questions below the currently selected question
- add question/hr/text adds a question after the currently selected question

PLAN-177 fix survey add/edit controls

---

db/seeds/format.seeds.rb

so we had a seed that recreated the "Other (add to notes)" format. That has been corrected

Plan-390 get rid of wrong other

---

app/models/person.rb

Logic that checked if state change updated does not work for a where().update() statement. Fixed so that the assignments will now update correctly when person is rejected or declined

fix logic for changing assigment based on person state change

---

db/migrate/20220620180039_person_exclusion_conflicts.rb

fix typo - extraneous lines in migration

---

db/migrate/20220620180030_add_duration_to_sched_view.rb
db/migrate/20220620180039_person_exclusion_conflicts.rb

I moved view creation to a helper, so for deployment I fixed the recent view migration to use that so as to avoid conflicts with startup checks as well

move view creation to a helper. So fix migrations to use that

---

app/javascript/conflicts/session_conflicts.vue

- this doesn't apply to in the flyout or edit tabs; just on the conflict sidebar. Also unified the display code

PLAN-487 Always show session name

---

app/javascript/surveys/edit-survey.vue
app/javascript/surveys/manage-survey.vue
app/models/survey.rb

@Gailbear we need the UI to allow for the description to be edited. I turned off the disable for title, but since description is grouped with the rest of the edit etc I think there is some untangling to do,

PLAN-402 allow edit of survey title and description

---

app/javascript/components/table_vue.vue

This fixes the problem of an enabled clone button for all tables where nothing has been selected

PLAN-239 The clone button is disabled if selected_items.length===0

---

db/migrate/20220707124302_fix_audit_ids.rb
db/structure.sql

This is a fix that is needed so that we can use the audits for change sheets when we publish the schedule

paper trail audit tables should use uuids

---

lib/tasks/chicon.rake

removed hugo rehersal from exclusion mapping as requested, adjusted rake so it is not recreated

PLAN-588 we do not want to map the hugo rehersal to exclusion

---

app/javascript/dashboard/dashboard.vue
app/javascript/people/people.js
app/javascript/people/people_table.vue
app/javascript/people/person_tabs.vue
app/javascript/profile/person_schedule_approval.vue
app/javascript/schedule/schedule_settings.vue
app/javascript/store/person_schedule_approval/person_schedule_approval.model.js
app/javascript/store/schedule_workflow/schedule_workflow.mixin.js
public/maintenance.html

- format date for schedule settings
- add last edited for person schedule approval
- disable “not set” as selectable radio on approval form
- show dashes in schedule approval columns until appropriate schedule is released
- draft comment and firm comment columns in people table, with ellipses tooltip
- blank out display in person box when state is not “no” but do not  delete data
- pull schedule workflow on profile tab load
- reverse order of live and draft tabs
- change the comment column in people table to be “notes”
- change signed in column to “last logged in”
- take out “opted in” column
- add home link to maintenance page

PLAN-596 PLAN-598 PLAN-599 fixes for draft schedule

---

app/controllers/sessions_controller.rb

since session count was added the derived col logic was updated in the query generator and old derived col definition for area was incorrect

fix the area search

---

app/javascript/people/people_table.vue
app/javascript/shared/tooltip-overflow-keep-newlines.vue

Created new tooltip component that preserves newlines

PLAN-603-tooltip-over-draft-firm-acceptance-comment-does-not-preserve-line-breaks

---

app/serializers/conclar/participant_serializer.rb
db/seeds/development/person.seeds.rb

I'd like to add the attendance type field to the participant output used for conclar as a tag so that we can add tags to the people page.

PLAN-672 Add participant attendance type as tag in conclar output

---

app/javascript/profile/session_ranker.vue
app/javascript/sessions/assign_participants.vue
app/javascript/store/table.mixin.js

table mixin is used for fetching collections with params. Not all collections should be paged. New default page breaks places were we do not want paged results. Added fetchAll which factors out common code and makes page optional.

PLAN-677 Stag paging issue

---

app/controllers/reports/schedule_reports_controller.rb

Small tweak so that is a session is added or dropped we do not need to also add to the title or description change tab

adjust pub diffs so add and drops do not also create info about title… 2.0

---

app/controllers/publication_dates_controller.rb
app/javascript/schedule/schedule_settings.vue
app/javascript/store/model.mixin.js
app/javascript/store/model.store.js
app/javascript/store/publication_dates.store.js
app/serializers/publication_date_serializer.rb
config/routes.rb
db/migrate/20220818022629_add_sent_external_to_publication_dates.rb
db/structure.sql

- new field sent_external on publication_dates
- also added a missing lock_version
- endpoints, store, and works with the model mixin
- added a patch to model mixin (and refactored patch selected to use it)
- made the data fetch reactive
- as a bonus: made reset buttons BRIGHT RED

PLAN-707 add external to pubs table (2.1.0)

---

app/controllers/reports/people_reports_controller.rb
app/controllers/reports/program_ops_reports_controller.rb
app/controllers/reports/session_reports_controller.rb
app/javascript/reports/reports_screen.vue

Reorder the Program Ops reports into more logical order.
Add descriptions for Participants with Social Media, Participants with Mismatching Session Environments and Attendance Types, Sessions Requiring Attendee Signups, Session Needs, Sessions and Minors, Room Sign Data for Mail Merge, Table Tent Data for Mail Merge, User Privileges.
Change titles for some reports to match above list. 
Capitalization changes to field names of Back of Badge.

PLAN-728 Reorder and add descriptions for new reports (2.1)

---

app/javascript/people/detail.vue

People flyout was showing Yes for livesteam allowed, recording allowed, and photographing allowed, regardless of the actual stored values (which can be seen on the people editor).

Change people flyout for stream & record & photo

---

app/javascript/reports/reports_screen.vue

Session data included needs to change from "all published sessions" to "all scheduled sessions with status of reviewed or draft" because that's how it can include invisible participants

Change session data description in Back of Badge

---

app/controllers/reports/program_ops_reports_controller.rb
app/javascript/reports/reports_screen.vue

Menu and descriptions:
--title of User Privileges for staff
--add S to Session and Minors
--Room Signs has separate columns for mods & participants
--Mismatched Sessions: person with "in person" att type is only incompatible with "virtual" session (not hybrid)
--extra word Sessions in Mismatched Sessions report

PLAN-751 and PLAN-754 fix wording reports

---

app/javascript/reports/reports_screen.vue

State explicitly that "published sessions" means that a publish has been done.
Modify wording of Airmeet Magic Links and Airmeet Diffs.

Small wording changes to Ops Reports

---

app/controllers/settings_controller.rb
app/javascript/administration/privacy_policy_link.vue
app/javascript/administration/terms_of_use_link.vue
app/javascript/constants/config.js
app/javascript/constants/strings.js
app/javascript/login/login.vue
app/javascript/surveys/question.mixin.js
app/mailers/application_mailer.rb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
config/initializers/devise.rb
lib/tasks/parameters.rake

Add the ability to configure the convention name, and the Terms of Use and Privacy Policy links that appear in the footer.

PLAN-774 PLAN-524 Configure convention settings

---

app/javascript/airmeet/airmeet_settings.vue
app/javascript/configurations/config_editor.vue
app/javascript/dashboard/dashboard.vue
app/javascript/integrations/airmeet.mixin.js
app/javascript/profile/availability_and_interests.vue
app/javascript/profile/person_details.vue
app/javascript/profile/person_summary.vue
app/javascript/sessions/session_summary.vue
app/javascript/shared/event-virtual.mixin.js
app/javascript/store/integration.store.js
app/javascript/store/model.store.js
app/serializers/integration_serializer.rb
lib/tasks/parameters.rake
package.json
yarn.lock

there are two new toggles that hide things:
- event_virtual which controls the showing and hiding of all participant-facing virtual information
- airmeet enabled is now honored and configurable. it controls the display of the airmeet sync buttons

PLAN-776 disable display of virtual participant settings

---

.github/workflows/deploy.yml

This adds the extra steps so that the docker image is pushed to the Github container registry and tagged accordingly. Also when a release is tagged (Vx.x.x) it will be tagged as latest etc.

add logic to put docker image in github reg

---

app/javascript/components/edit_button.vue
app/javascript/profile/dl_person.vue
app/javascript/profile/person_details.vue

- name of preferences fields is now "additional information"
- all text now properly italicized

PLAN-811 style fixes

---

Gemfile.lock
app/services/mail_service.rb
app/workers/mailing_worker.rb
script/planorama_start.sh

Mailing worker has following changes
- make sure that place of last send is saved so that resume does not resend prior messages (transaction issue)
- add more exceptions to catch
- ensure the fail messages are saved in the mail history and marked as failed (do not stop processing rest of mailing)

PLAN-794 - Mailing fixes

---

app/controllers/surveys_controller.rb
app/javascript/surveys/survey-page.vue
app/javascript/surveys/survey-settings-tab.vue
app/serializers/survey_serializer.rb
db/migrate/20230304203222_change_survey_column_name.rb
db/structure.sql

New survey setting: "Allow this survey to be taken without assignment"
When you check that and it's published, it lets you take the survey.

PLAN-822 add unassigned to surveys

---

config/initializers/mailer.rb

This is needed so that we have extra options for the mail config

add option for SMTP and open SSL

---

app/javascript/shared/email_field.vue
app/javascript/surveys/survey_question.vue

Because the email field wasn't passing up the blur event, it wasn't triggering the saveResponses method like it was supposed to.

PLAN-830 fix email survey field

---

app/javascript/login/login_password_field.vue

- now actually sends the server call; it wasn't before because valid is very rarely true, just null.
- don't send backend check on confirmation
- mark validation as true on confirmation when matching (for green checkmark)
- fix confirmation validation message

PLAN-841 fix remote validation

---

app/javascript/surveys/options-question.vue
app/javascript/surveys/survey_question.vue

We allowed you to add formatting, but we didn't ever render it; though i could SWEAR i implemented this at some point. Ah well, it's now implemented again!
Note: you can no longer use the html editor on dropdowns, as the browsers don't support styling that.

PLAN-846 Format survey options for questions

---

app/javascript/login/login_screen.vue

This is a prod issue. There is a double redirect that causes the router to error when redirecting to survey - causing participant confusion.
This is because the logic was in two places - I have commented out the login in the login screen so that the router handles it.

fixes the double redirect which causes render issue

---

app/controllers/integrations_controller.rb
app/controllers/settings_controller.rb
app/javascript/app.router.js
app/javascript/integrations/clyde.mixin.js
app/javascript/integrations/clyde_settings.vue
app/javascript/login/login.vue
app/javascript/login/login_integrations.vue
app/javascript/login/login_small_print.vue
app/javascript/profile/registration_link.vue
app/javascript/store/integration.store.js
app/javascript/store/login_integrations.mixin.js
app/models/integration.rb
app/policies/integration_policy.rb
app/serializers/integration_serializer.rb
app/services/airmeet_api_service.rb
app/services/clyde_service.rb
config/routes.rb

- Move clyde settings to integrations table
- Add setting for button text
- Allow the user to enable/disable clyde both in general and as a registration integration
- Move login integrations to a "hidden" screen on the login page

PLAN-863 PLAN-864 PLAN-855 login changes

---

app/controllers/auth/omniauth_callbacks_controller.rb
app/javascript/app.router.js
app/javascript/integrations/clyde.mixin.js
app/javascript/integrations/clyde_settings.vue
app/javascript/login/login.vue
app/javascript/login/login_clyde.vue
app/javascript/login/login_integrations.vue
app/javascript/store/login_integrations.mixin.js
app/services/identity_service.rb

- move clyde button to another page
- reinstate other potential login buttons to the main login page
- make link text configurable
- add warning text about the log in linking your account

PLAN-864 PLAN-867 Make login the way Ian wants it

---

app/javascript/login/iea-modal.vue
app/javascript/profile/availability_and_interests.vue
app/javascript/shared/toast-mixin.js

Remove the central timezone from the availability instructions (so it is not Chicon specific)
I also removed some other Chicon references and use the event email in the toast error display (instead of chicon's one)

Plan 874 text fixes

---

app/controllers/page_contents_controller.rb
app/javascript/administration/admin_component.vue
app/javascript/administration/playground_component.vue
app/javascript/app.router.js
app/javascript/components/plano_editor.vue
app/javascript/constants/strings.js
app/javascript/dashboard/dashboard.vue
app/javascript/page-content/page_content.mixin.js
app/javascript/page-content/page_content_display.vue
app/javascript/page-content/page_content_editor.vue
app/javascript/store/model.store.js
app/javascript/store/page_content.store.js
app/models/page_content.rb
app/policies/page_content_policy.rb
app/serializers/page_content_serializer.rb
config/routes.rb
db/migrate/20230924145027_create_page_contents.rb
db/structure.sql
lib/tasks/rbac.rake
spec/factories/page_contents.rb
spec/requests/page_contents_spec.rb
test/models/page_content_test.rb

Here is the code to support page text from the db
It will take content from the slot if the content corresponding to name does not exist in the DB
```
<page-content-display name="dashboard-intro">
some other stuff
</page-content-display>
```
There is a test editor in the /#/playground that can be used to edit/create the text using a CKeditor. There is a drop down, just add the names of the text areas that you want to the drop down and the editor to create. We can use this for any customizable area ...

Plan 873 landing page text

---

app/serializers/session_serializer.rb

Fixes the missing session format in the serialized objects and hence the display in the profile

PLAN-881 fix the serialization of the session format

---

app/views/xml_templates/schedule.nokogiri

indesign xml generation breaks.
Put in guard for this case
Not urgent - this is a fix to put in some future release

Issue when an item does not have a format,

---

Gemfile.lock
README.md
Taskfile.yaml

This adds the ability to use [Task](https://taskfile.dev/) which is basically just a tool that lets you save commands that you need to run frequently. I added most of the things that were in `docker.rake` to `Taskfile.yaml`, and added instructions to the Readme. The changes to Gemfile.lock are just due to running `bundle install` locally for the sake of my IDE.

Adding Task support and instructions

---

app/services/url_service.rb

fix any extra slash in start of the path when building URL

Fix double slash in URL for mailings

---

app/javascript/store/tags.mixin.js

So far, this is only the frontend part where we stop using the frontend tag formatter. @balen will add the backend parts.

PLAN-923 Fix tag capitalization issues

---

app/javascript/profile/session_search.vue
app/javascript/profile/session_selector.vue

Saved filter for session selection only applies if the profile is for the current logged in user

PLAN-921 Do not keep filter for other people's session selection

---

app/javascript/sessions/datetime_picker.vue

Let JS do its thing and not force to UTC (UTC has no concept of daylight savings)

PLAN-947 Fix timezone issue with daylight savings boundary

---

app/javascript/profile/person_surveys.vue

Problem is that the person changes in the store
when the related surveys are fetched. Which
re-triggers the watch on person and so on

PLAN-953 Fix multiple load of surveys for person_surveys

---

app/javascript/sessions/datetime_picker.vue

Fixes a problem where we are in con TZ in the editor and we munge the
time as if it is UTC and end up off by the hour difference

PLAN-994 Be consistent with timezone

---

app/controllers/schedule_controller.rb
app/workers/publication_worker.rb

Using the sent external for the gatekeeping flag. The latest sent external publish
will be the one that ConClar gets

Plan 983 snapshot and gate for conclar

---

app/javascript/people/people_admin_tab.vue

The resync works. It does not depend on OAuth. It uses the OAuth identity if it is there or the reg_id for the person. Since the OAuth id is not there it uses the reg id for the person.
Resync only works if the person has a reg_id i.e. they were already associated with a registration.
```
identity = person.oauth_identities.where(provider: 'clyde').first
reg_id = person.reg_id || identity&.reg_id
```
However the button was commented out so I put it back in. Tested it and I saw the new data come back from Clyde.

PLAN-785 Put the button back in the UI

---

app/javascript/shared/convention-timezone.mixin.js

both the start and end days needs to be in the convention timezone. Otherwise if the users computer's timezone is sufficiently different than the cons (like 8 or more hours) the days will be off by one.

Fix timezone for start and end day

---

app/javascript/schedule/schedule_calendar.vue

We are supposed to filter to sessions that are scheduled, but apparently the filter was
not applied so we got all of them. So more data is downloaded than needed + the UI does
more work processing data that is not going to be put on the calendars.

PLAN-1044 Fetch does not use the filter, fetchAll does.

---

.dockerignore
.gitignore
README.md
Taskfile.yaml
docker-compose-dev.yml
lib/tasks/docker.rake

direnv uses `.envrc` files as configuration, which means that the proposed .envrc file format in the README/task file conflict with a common environment management tool.
This replaces all .envrc references with .env, which a more common form for docker as well as being suported as an environment sideload with direnv

Change the .env file so that it doesn't conflict with direnv
