Dockerfile
app/javascript/model.js
db/migrate/20210320194037_remove_unwanted_sort_default_vals.rb
db/structure.sql

remove defaults form sort order of rooms and venues

Henry working

---

.dockerignore

Henry, please review and see if this is something you want to add.

Suggested dockerignore file per docs I have seen

---

db/seeds/development.seeds.rb

I expanded the file that creates dummy persons for the development db.

Updated file that creates dummy people for db. Fills out more fields.

---

db/seeds/development/userdev.seeds.rb
db/seeds/test/usertest.seeds.rb
spec/factories/room.rb
spec/factories/setup_type.rb
spec/factories/venue.rb
spec/models/room_spec.rb
spec/models/venue_spec.rb

Just a few small updates. Renamed the seed file that creates a development environment user and added one that creates some test environment users. Also worked on some factorybot tests.

Update to a couple of seed files and to some factorybot tests

---

db/seeds/development/userdev.seeds.rb
db/seeds/person.seeds.rb
db/seeds/survey.seeds.bad
db/seeds/survey.seeds.rb
db/seeds/test/usertest.seeds.rb
spec/factories/person.rb
spec/factories/survey.rb
spec/models/programme_assignment_role_type_spec.rb
spec/models/survey_spec.rb

Added 2 additional users for development env.
Updated person seeds file.
Created survey seeds file.
Created survey tests file.

Update to seed files and tests

---

app/models/person.rb
spec/models/person_spec.rb

I made the last_name field required in the person model per Henry.
I made some additional tests and updated some.
There are 2 tests that currently fail due to incorrect logic that creates the derived field of published_name. Henry will be fixing this logic. Then the tests should work.

Updates to tests, made last_name required

---

db/seeds/development/userdev.seeds.rb
db/seeds/person.seeds.rb
spec/models/person_spec.rb

Expanded the person seed to create twitter and facebook and other handles.
Updated the userdev seed to ensure it runs after the person seed.
A couple minor updates to the test descriptions for the person tests.

Updated person and userdev seeds and minor update to person tests

---

docs/_config.yml
docs/index.md
docs/privacy.md
docs/tandc.md

merging in Gail's index page and the two newly made Privacy and T&C pages.  stubs all around

merge docs into main

---

db/seeds/development/survey.seeds.rb

trying this thing.  with my own questions.

trying to make my own surveys with  'real' questions

---

db/seeds/development/survey.seeds.rb

now doing 2

---

app/views/layouts/_side-navbar.html.erb
db/seeds/development/survey.seeds.rb

Icons have been added. Anna should confirm the survey icon as the icon in her doc was from the noun project, so I used something kinda similar from bootstrap.

Add left nav icons. Fix survey seed.

---

app/javascript/surveys/edit-survey-page.vue
app/javascript/surveys/next-page-picker.vue
app/javascript/surveys/options-question.vue
app/javascript/surveys/survey_sidebar.vue
db/seeds/development/userdev.seeds.rb
db/seeds/person.seeds.rb
db/seeds/staging/userstag.seeds.rb
script/planorama_start.sh

Updated a few seed files. Added a staging folder and seed, but it might not be useful. Doesn't hurt anything, I think. :-)

Updated seed files

---

docs/index.md
docs/privacy.md

adding the text of the data privacy and protection policy

adding the text of the data privacy and protection policy

---

app/controllers/people_controller.rb
app/controllers/survey/pages_controller.rb
app/controllers/survey/questions_controller.rb
app/models/survey/answer.rb
app/models/survey/page.rb
app/serializers/survey/answer_serializer.rb
config/initializers/mailer.rb

The generated mail for forgot password should have https. This addresses that issue.

Fix the mail URL protocol

---

app/javascript/people/people_sidebar.vue
app/javascript/people/people_surveys_tab.vue

The surveys tab on the person flyout is displaying correctly.

Add surveys tab to person flyout

---

app/javascript/constants/strings.js
app/javascript/store/model.mixin.js

changed error messaging to have real words, and added some new messages

Update strings.js - not done yet

---

README.md

Added instructions for recovering from the yarn build problem

Addrsses a build problem

---

app/controllers/people_controller.rb
app/javascript/components/sheet_importer_vue.vue

fix import condition

---

app/javascript/app.router.js
app/javascript/store/person_session.store.js

this should fix us not having the session when first checking for login.

fix flicker

---

app/javascript/constants/strings.js
app/javascript/surveys/linked-fields.js

strings fixes and linked field stuff

---

app/javascript/people/people_sidebar.vue
app/javascript/people/people_surveys_tab.vue
app/javascript/surveys/survey_table.vue

Flyout now displays the table of surveys assigned to that person. Still TODO: clicking on the survey shows their responses

People flyout 2

---

app/javascript/constants/strings.js
app/javascript/surveys/edit-survey-question.vue
app/javascript/surveys/linked.mixin.js

Also display them nicer when they are linked.

Update labels for linked fields

---

app/javascript/app.router.js

(Also named con_roles to not get confused with the eventual security 
roles)

fix for isAdmin

---

app/javascript/surveys/linked.mixin.js
app/javascript/surveys/question.mixin.js

Better default labels for linked fields

put in better default labels for new field types

---

app/javascript/components/email_address_editor.vue
app/javascript/components/validated_social.vue
app/javascript/configurations/config_editor.vue
app/javascript/profile/availability_and_interests.vue
app/javascript/profile/availability_calendar.vue
app/javascript/profile/person_details.vue
app/javascript/profile/profile-screen.vue
app/javascript/profile/session_limit_editor.vue
app/javascript/social-media/simple-social.vue
app/javascript/surveys/survey_question.vue
config/environments/production.rb
config/environments/staging.rb

Please check the social media validation regexs.
Youtube channels for example always start UC- with a alphanumeric string (with periods allowed) of at least a certain length.
I fixed website so that it allows uppercase.

update some of the social media validation rules

---

app/javascript/agreements/agreement_editor.vue
app/javascript/agreements/agreement_manager.vue

Fixes PLAN-237
When i create and save an agreement, it does not appear in the table of agreements until i refresh the page or the roll up and unroll the accordion screen.  
It should force a refresh of the table
Reporter: anna

Agreements table refresh on save of new agreement

---

app/javascript/app.router.js
app/javascript/profile/session_ranker.vue
app/javascript/profile/session_selector.vue
app/javascript/rbac/frontend-model.js
app/javascript/rbac/permission-checkboxes.vue
app/javascript/rbac/rbac-screen.vue
app/javascript/rbac/static-permissions.js

splatted on a screen that is not connected to any person or role in particular, to start implementing the actual access and for review purposes.

field of checkboxes pass 1

---

db/seeds/development/agreement.seeds.rb
db/seeds/development/area.seeds.rb
db/seeds/development/format.seeds.rb
db/seeds/development/session.seeds.rb
db/seeds/staging/area.seeds.rb
db/seeds/staging/format.seeds.rb

This contains small updates to a couple of existing seeds and then some new seeds for development and staging environments.

Created some new seed files for dev and staging env

---

app/javascript/components/model_select.vue
app/javascript/components/search_vue.vue
app/javascript/packs/application.js
app/javascript/sessions/area_select_for_search.vue
app/javascript/sessions/session.js
app/javascript/stylesheets/style.scss

working area with vue-select

---

app/javascript/login/forgot_password.vue

fix spelling of receive

---

app/javascript/constants/strings.js

SURVEY_NOT_ASSIGNED: added period
IEA_FAILURE_TO_SIGN: fixed spelling of statements
QUESTION_ORDER_SAVE_SUCCESS: added period
QUESTION_SAVE_SUCCESS: added period
QUESTION_DELETE SUCCESS: added period
QUESTION_DUPLICATE_SUCCESS: added period
QUESTION_ADD_SAVE_SUCCESS: added period
QUESTION_UNCHANGED: added period
ANSWER_SAVE_SUCCESS: added period
ANSWER_ADD_SUCCESS: added period
SESSION_INTEREST: added period to 8 strings
SESSION_RANKING_ERROR: added "which" to fix grammar
CONFIGURATION_SAVED_SUCCESS and ...ERROR: added 2 periods
CREATE_SESSION_LIMIT_SUCCESS and ...ERROR: added 2 periods and fixed capitalization
UPDATE_PERSON_EXCLUSION_ERROR: fixed capitalization
GET_PERSON_EXCLUSION_ERROR: fixed capitalization
UPDATE_AVAILABILITY_ERROR: fixed capitalization
ADD_EMAIL_ERROR: fixed …

Fix punctuation and typos

---

app/javascript/components/icon_button.vue
app/javascript/components/plano_modal.vue
app/javascript/schedule/room_selector.vue
app/javascript/schedule/schedule_screen.vue
app/javascript/stylesheets/style.scss

put the rooms into a modal, which comes out of a gear at the top-right of the scheduler

 make rooms into a modal

---

app/controllers/concerns/resource_methods.rb
app/controllers/room_sets_controller.rb
app/controllers/rooms_controller.rb

allow paging of not paginated if wanted by client

rooms and room sets not paginated

---

app/javascript/schedule/room_selector.vue
app/javascript/schedule/schedule_screen.vue
app/javascript/store/model.store.js
app/javascript/store/room.store.js

This will only last if you don't refresh. After that all bets are off.
#time 1h

PLAN-275 Retain room selection locally

---

app/javascript/navbar/top-navbar.vue

- had to adjust the placement of the buttons a bit, but i think it's still close enough

PLAN-228 put user email in top nav

---

app/javascript/navbar/top-navbar.vue

PLAN-228 - fix sync error with email display

---

app/services/mail_service.rb

fix mailer assigning person to survey that they are already assigned to

Plan-302 do not try to assigne person more than once to a survey

---

app/javascript/constants/strings.js

updated error message for profile editing and error message on social media fields validation

PLAN-311 string updates

---

app/javascript/components/model_loading_overlay.vue
app/javascript/constants/strings.js
app/javascript/packs/application.js
app/javascript/people/person_tabs.vue
app/javascript/profile/dl_person.vue
app/javascript/profile/person_summary.vue
app/javascript/sessions/person_details.vue

should be 'Not Specified' if null and 'Restricted' if undefined, with styling.

PLAN-282 Change N/A to other things

---

app/controllers/sessions_controller.rb
app/javascript/app.router.js
app/javascript/components/model_select.vue
app/javascript/sessions/assignment_state.vue
app/javascript/sessions/session_edit.vue
app/javascript/sessions/session_notes.vue
app/javascript/sessions/session_sidebar.vue
app/javascript/sessions/session_summary.vue
app/javascript/sessions/session_tabs.vue
app/javascript/sessions/view_participant_type.vue
app/javascript/sessions/view_participants.vue
app/javascript/store/format.store.js
app/javascript/store/model.mixin.js
app/javascript/store/model.store.js
app/javascript/stylesheets/custom.scss
app/javascript/stylesheets/style.scss
app/serializers/session_serializer.rb
db/migrate/20220531011606_add_proofed_to_session.rb
db/structure.sql

- scheduled ticky switch
- proof field & ticky switch
- assigned participants view on flyout
- notes on flyout
- added disabled conflict tab
- format single select in general tab
- commented out tags select in general tab

PLAN-315 session p1 improvements part 1

---

config/brakeman.ignore

update brakeman ignore

---

app/javascript/conflicts/session_conflicts.vue

- remove extraneous X
- date on new line
- link for participant page
- no scroll bar

PLAN-333 conflict styling fixes

---

app/javascript/constants/strings.js
app/javascript/surveys/survey-page.vue

created 2 strings to better state the linked fields caveat in surveys

PLAN-301 Update strings.js for better linked string

---

app/models/session.rb

fix issue to disallow null for duration - backend

PLAN-340 Staging duration fix

---

app/javascript/surveys/edit-survey-question.vue

- Delete and duplicate
screenshots in ticket https://chicon-planorama.atlassian.net/browse/PLAN-296

PLAN-296 add tooltips to question edit buttons

---

app/javascript/surveys/edit-survey-question.vue
app/javascript/surveys/survey_question.vue

- add classic editor to question editing
- display result using v-html

PLAN-179 make textonly fields html

---

app/javascript/surveys/response.mixin.js

- now returns the email itself instead of the email object

PLAN-304 fix linked email address

---

app/controllers/reports_controller.rb
lib/tasks/rbac.rake

Fixes permission on do not assign with and running the schedule by person

Plan-364 and Plan-367

---

lib/tasks/rbac.rake

PLAN-377 fix rbac for participant availability

---

app/controllers/reports_controller.rb

Also fixed so that only participant, invisible and moderator are listed

Plan-369 Fixed so that sessions without assignments get listed.

---

app/javascript/sessions/session_tabs.vue

Fixes 371 by keep the unassigned in list

PLAN-371 Keep unassigned in list for now

---

app/javascript/sessions/session_tabs.vue

they had temporarily dissappeared off the potential participants list

PLAN-391 make uninterested participants appear 

---

app/javascript/constants/strings.js
app/javascript/surveys/survey_sidebar.vue

- Disable menu item and add tooltip

PLAN-317 disallow deletion of published survey

---

app/controllers/reports/conflict_reports_controller.rb
app/javascript/reports/reports_screen.vue
app/models/conflicts/person_back_to_back_to_back.rb
app/policies/reports/conflict_report_policy.rb
config/routes.rb
db/migrate/20220616160624_create_back_to_back_to_back_view.rb
db/structure.sql
lib/tasks/rbac.rake

Code to do back to back to back ...

PLAN-349 - back to back to back !!!

---

app/javascript/surveys/edit-survey-controls.vue
app/javascript/surveys/view-responses.vue

- new questions now show on the page
- questions in response filtering dropdown are now truncated at 100 characters

PLAN-285 PLAN-320 fix survey bugs

---

app/controllers/survey/submissions_controller.rb

in spreadsheet do not include data or column for sensitive fields

PLAN-425 fix access to sensitive fields

---

app/controllers/survey/submissions_controller.rb

in spreadsheet do not include data or column for sensitive fields

fix access to sensitive fields

---

app/controllers/sessions_controller.rb
app/javascript/sessions/view_participant_type.vue
app/serializers/session_serializer.rb

Fix by returning assignments in the session and using that relationship

PLAN-433 - Fix the session assigments display in session flyout

---

app/controllers/survey/submissions_controller.rb

fix submission state params

---

app/controllers/sessions_controller.rb
app/javascript/conflicts/session_conflicts.vue

Nesting the session assignments with the session in the json-api response is one source of performance problem for the vuex json api store

PLAN-439 PLAN-440 Fix conflict display and performance side effects

---

app/controllers/session_assignments_controller.rb
app/serializers/session_assignment_serializer.rb

We need the people in the session assignments ...

PLAN-443 make sure people are loaded if need be for assignments

---

app/controllers/conflicts/session_conflicts_controller.rb
app/lib/migration_helpers/plano_views.rb
app/models/session.rb
app/serializers/session_serializer.rb
db/migrate/20220620215358_adjust_all_conflict_views.rb
db/structure.sql
lib/tasks/submission.rake

Improve views
Fix conflict ordering for reports

PLAN-406 Dev fix conflict ordering

---

app/javascript/people/people_session_names.vue
app/javascript/people/people_table.vue

If you are mass rejecting, for each participant, show the names of the panels
they will be removed from if you do, or show "No Sessions"
Also features a copy to clipboard button that mostly works.

PLAN-441 show names of rejected/declined panels

---

app/javascript/sessions/session_edit.vue
app/javascript/sessions/session_sidebar.vue

PLAN-435 tech notes and participant notes

---

app/controllers/reports/conflict_reports_controller.rb
app/controllers/reports/session_reports_controller.rb
app/controllers/reports_controller.rb

PLAN-477 Column heading fixes

---

app/javascript/people/people_table.vue

PLAN-484 Minor report changes continued

---

app/javascript/app.vue
app/javascript/components/magical_reload.vue
app/javascript/conflicts/session_conflicts.vue
app/javascript/schedule/room_selector.vue
app/javascript/schedule/schedule_screen.vue
app/javascript/store/app.store.js
app/javascript/store/model.store.js

Configurable text and tooltip.
Still to come "x minutes/hours ago" format for timestamp.

PLAN-479 Magical Reload button - works for every "screen" page

---

app/javascript/reports/reports_screen.vue

also fix scrolling on the reports page

PLAN-492 hide borked reports

---

app/controllers/conflicts/session_conflicts_controller.rb
app/javascript/conflicts/session_conflicts.vue
app/javascript/constants/strings.js
app/javascript/store/model.mixin.js
app/javascript/store/session_conflict.mixin.js
app/javascript/store/session_conflict.store.js
app/models/ignored_conflict.rb
app/models/session.rb
app/policies/conflicts/session_conflict_policy.rb
app/serializers/conflicts/session_conflict_serializer.rb
config/routes.rb
db/migrate/20220628121934_create_ignored_conflicts.rb
db/structure.sql
lib/tasks/rbac.rake
test/factories/ignored_conflicts.rb
test/models/ignored_conflict_test.rb

PLAN-385 and PLAN-418 conflict ignoring

---

app/controllers/conflicts/session_conflicts_controller.rb
app/javascript/components/table_vue.vue
app/javascript/sessions/session.js

So now we get the other sessions for the conflict and their indicators 
will update
PLAN-410

PLAN-410 fix selection issues with vuex jsonapi store and included models

---

app/controllers/conflicts/session_conflicts_controller.rb
app/controllers/reports/conflict_reports_controller.rb
app/lib/migration_helpers/plano_views.rb
app/serializers/conflicts/session_conflict_serializer.rb
db/migrate/20220629132145_add_indexes.rb
db/structure.sql

Emergency changes for session view issues

PLAN-499 view fixes etc

---

app/controllers/reports/session_reports_controller.rb
app/controllers/reports_controller.rb

Non-Accepted Participants on Scheduled Sessions
Schedule by Participant

PLAM-499 Fixes for

---

app/javascript/sessions/session_schedule.vue

PLAN-372 validate duration

---

app/javascript/components/icon_button.vue
app/javascript/conflicts/ignore_button.vue
app/javascript/conflicts/session_conflicts.vue

PLAN-495 Make the ignore button into an icon

---

app/javascript/packs/application.js
app/javascript/sessions/view_participants.vue

- Also set the universal default animation for skeletons to "fade"

PLAN-389 Add skeleton to participant loading

---

app/javascript/schedule/schedule_calendar.vue
app/javascript/schedule/schedule_day.vue

PLAN-387 add spinner to sched load

---

app/models/person.rb

Fixes the email check that was causing tests to fail

Dev fix rspec tests

---

app/javascript/conflicts/session_conflicts.vue
app/javascript/schedule/schedule_calendar.vue
app/javascript/schedule/schedule_day.vue
app/javascript/schedule/schedule_screen.vue

But dependent sessions will not update on delete from grid. That needs the grid refreshed

PLAN-509 fix conflict refresh on move

---

app/javascript/conflicts/session_conflicts.vue

better code for promise assignment... as per Gails suggestion

fix promise assignment

---

app/javascript/reports/reports_screen.vue

Everything else seemed correct and current. I've just added placeholders for two missing reports.

PLAN-430 added the two missing Scheduling reports as commented out entries

---

app/controllers/sessions_controller.rb
app/javascript/sessions/session.js
app/javascript/sessions/session_edit.vue
app/javascript/sessions/session_fields.mixin.js
app/javascript/sessions/session_sidebar.vue
app/javascript/sessions/session_summary.vue
app/javascript/sessions/session_table.vue
lib/tasks/chicon.rake
script/planorama_start.sh

- add room_set (though it's not displaying on the flyout yet)
- add public schedule visibility

PLAN-436 session improvements p3

---

app/javascript/packs/application.js
app/javascript/people/people_session_names.vue
package.json
yarn.lock

using Vue clipboard component that wraps clipboard.js

PLAN-503 copy to clipboard component

---

app/javascript/sessions/session_fields.mixin.js

PLAN-540 add missing return statement

---

app/javascript/people/person_tabs.vue

PLAN-541 disable schedule tab for now

---

app/views/devise/mailer/password_change.html.erb

PLAN-173 Update password_change.html.erb

---

app/javascript/sessions/session_edit.vue
app/javascript/sessions/session_summary.vue

Adding ids

---

app/controllers/session_assignments_controller.rb

ignoring case with this DB is not going to be done before Chicon. The rest is ok

PLAN-548 fix ordering in session participants

---

app/models/session.rb

I think this deals with the issue Debbie found

make sure count uses the same criteria

---

app/javascript/people/people.js

Added a list of operators to the Status field in people.js

PLAN-241-add-operator-to-status-search-for-people

---

app/controllers/people_controller.rb
app/javascript/profile/person_schedule.vue
app/lib/migration_helpers/plano_views.rb
app/models/person_schedule.rb
app/policies/person_policy.rb
app/serializers/person_schedule_serializer.rb
app/serializers/person_serializer.rb
app/services/session_service.rb
config/routes.rb
db/structure.sql
lib/tasks/rbac.rake

This changes the structure, it is faster and better for snapshots

PLAN-517 Better implementation for person schedule

---

app/javascript/people/person_tabs.vue
app/javascript/profile/person_schedule.vue
app/models/person_schedule.rb
app/serializers/person_schedule_serializer.rb

now with more streamlined data!

PLAN-446 use new endpoint for live schedule tab

---

app/controllers/reports/session_reports_controller.rb

to put in 1.5.1 to fix report issue

fix issue with nil start time

---

app/models/session.rb

Speed up the query by at least a factor of 4

PLAN-580 Speed up session retreival

---

app/controllers/reports/session_reports_controller.rb
app/controllers/reports_controller.rb
app/models/session.rb

Fix reports for sessions with no format

PLAN-583 Fix for session query

---

README.md
docs/index.md

PLAN-581 update the version numbers

---

app/javascript/components/table_vue.vue
app/javascript/mailings/mailings_manager.vue

Added the eye and trash icons to the View and Delete buttons in mailings_manager.vue
added the eye icon to the view button in the table_vuew.vue component

PLAN-529-mailing-tab-needs-to-have-icon-buttons-with-tooltips

---

app/controllers/people_controller.rb
app/controllers/sessions_controller.rb
app/javascript/administration/admin_component.vue
app/javascript/constants/strings.js
app/javascript/people/person_tabs.vue
app/javascript/profile/person_draft_schedule.vue
app/javascript/profile/person_live_schedule.vue
app/javascript/profile/person_schedule_approval.vue
app/javascript/profile/person_schedule_display.vue
app/javascript/schedule/schedule_settings.vue
app/javascript/store/model.store.js
app/javascript/store/schedule.store.js
app/javascript/store/schedule_status.mixin.js
app/policies/session_policy.rb
config/routes.rb
db/structure.sql
lib/tasks/rbac.rake

Missing some backend hookups but otherwise seems to work. Includes a reset endpont for testing purposes, that won't actually work if you click it in production.

PLAN-587 PLAN-522 PLAN-515 PLAN-575 PLAN-579 Draft schedules and approval

---

app/controllers/people_controller.rb
app/controllers/person_schedule_approvals_controller.rb
app/controllers/schedule_snapshots_controller.rb
app/javascript/people/people.js
app/javascript/people/people_table.vue
app/policies/schedule_snapshot_policy.rb
app/serializers/person_schedule_approval_serializer.rb
app/serializers/person_serializer.rb
app/serializers/schedule_snapshot_serializer.rb
app/serializers/schedule_workflow_serializer.rb
config/routes.rb

Plan 574 approval cols

---

app/javascript/sessions/datetime_picker.vue

This is PLAN-614 to fix the production but with the session time/date editor.
It has already been merged into staging and tested a bit there

PLAN-614 fix session date editor locale issues

---

app/javascript/people/people_admin_tab.vue
app/javascript/people/person_tabs.vue

Also, fix a bug with dynamic addition and deletion of tabs and index numbering that i discovered while doing 593.

PLAN-593 add status display to admin tab

---

app/javascript/dashboard/dashboard.vue
app/javascript/profile/person_schedule_display.vue

changes the dashboard content when the schedule workflow changes.

PLAN-604 PLAN-605 see current schedule on dashboard

---

app/controllers/sessions_controller.rb

PLAN-597 param key is not symbol (1.6.2)

---

app/javascript/components/table_vue.vue

Tooltips in the table component were changed as requested

PLAN-589-capitalize-remaining-tooltips-in-admin-mailings-tab-change-text-of-one

---

app/javascript/surveys/survey_sidebar.vue

PLAN-393-survey-link-icon-needs-to-be-changed

---

app/controllers/mailings_controller.rb
app/javascript/mailings/mailings_table.vue
app/services/session_service.rb

also fix condition for testing workflow for sched url

plan-422 sort is also defined in the JS

---

lib/tasks/chicon.rake

As requested by program DH - keeping list up to date in the rake

rooms added

---

app/controllers/application_controller.rb
app/controllers/schedule_controller.rb
app/controllers/sessions_controller.rb
app/models/publication_date.rb
app/models/publication_status.rb
app/models/publish_snapshot.rb
app/policies/session_policy.rb
app/services/publication_service.rb
app/services/session_service.rb
app/workers/publication_worker.rb
config/routes.rb
db/migrate/20220801152151_adjust_pub_dates.rb
db/migrate/20220801173704_create_publish_snapshots.rb
db/structure.sql
lib/tasks/publications.rake
lib/tasks/rbac.rake
test/factories/publish_snapshots.rb
test/models/publish_snapshot_test.rb

Put in the logic for publish and added simple cache for conlcar
Also endpoint to initiate publish async worked ( /session/schedule_publish) is what the publish button should call

plan-620 plan-619 publish process and conclar

---

app/javascript/people/person_tabs.vue
app/javascript/profile/person_email_tab.vue

PLAN-450 lightweight email tab.

---

app/views/xml_templates/schedule.nokogiri

Session areas are not for public (only used internally for planning)

remove areas from pubs XML

---

app/javascript/reports/reports_screen.vue

Make these descriptive lines consistent with wording of other reports

Livestream, recording exclusion word tweaks

---

app/javascript/schedule/schedule_settings.vue

Only hide button in prod so we can still test in staging and dev

Hide the parts that do not have backend functionality from all envs

---

app/controllers/schedule_controller.rb

Needed to remove an inadvertent wraopper

fix conclar json for published schedule

---

config/initializers/logger.rb
docker-compose-prod.yml

tweaks for logs to files

---

app/models/published_session.rb
app/models/session.rb
app/serializers/conclar/session_serializer.rb

Add format
Change order of participants

conclar tweaks

---

app/javascript/login/new_password.vue
app/views/devise/mailer/reset_password_instructions.html.erb
config/initializers/devise.rb

Increase the reset token timeout from 2 to 24 hours
Put a message in the email so people know

Up reset token timeout

---

app/serializers/conclar/session_serializer.rb

Changes to the session tags in the output used by ConClar.

PLAN-673 Update sessions tags

---

app/serializers/conclar/participant_serializer.rb

Fixed the bug that happens when attendance type is nil.

PLAN-672 Check that attendance type exists

---

app/serializers/conclar/participant_serializer.rb
app/serializers/conclar/session_serializer.rb

Updated the conclar output of tags to use the new format that conclar uses.

PLAN-673 Update conclar tags output to use new format

---

app/javascript/schedule/schedule_settings.vue

they work etc. this is not a great message.

PLAN-608 publish controls

---

app/javascript/reports/reports_screen.vue

In Participants: Participants moderating at least one session
In Sessions: Daily Grid

Add descriptive info for 2 new reports PLAN-680

---

app/javascript/sessions/session_edit.vue
app/javascript/sessions/session_sidebar.vue

Change to use audience size for signups

signups should use audience size

---

app/controllers/publication_dates_controller.rb
app/javascript/schedule/schedule_settings.vue

- doesn't show up in prod
- also make the endpoint work

PLAN-682 publication reset button (2.0)

---

app/serializers/conclar/participant_serializer.rb
app/serializers/conclar/session_serializer.rb

Fix a few tags provided to conclar to be more readable.

PLAN-689 PLAN-690 fix conclar fields

---

app/controllers/reports/session_reports_controller.rb

Sessions Streamed and Recorded: removed hyphen from Live-Streamed column heading, changed Time to Start Time
Daily Grid: changed Time to Start Time

PLAN-693 tweak column headings

---

app/javascript/reports/reports_screen.vue

Back of Badge
Scheduled Sessions Streamed and/or Recorded

Add descriptions to new reports PLAN-683

---

docs/index.md

using shields.io to provide version information based off current releases

no-more-manual-versions

---

app/serializers/conclar/session_serializer.rb

Remove venue from the location data being sent to conclar.

PLAN-702 Remove venue from data sent to conclar

---

app/controllers/reports/program_ops_reports_controller.rb

Fix bug with concat string to int

can not concat string  to int

---

app/controllers/publication_dates_controller.rb
app/controllers/reports/schedule_reports_controller.rb

Need to ensure that people do not try to do publish changes during a publish reset
Also fix condition for new sessions state change without time or room

fix condition and ensure nothing is done during a reset

---

app/javascript/reports/reports_screen.vue

New field duration was added and needed to be added to descriptive text.

Daily Grid report description update for duration

---

app/controllers/application_controller.rb

Need to put exceptions in logs so we can see what happens

Change report fixes

---

app/controllers/reports/schedule_reports_controller.rb
app/services/change_service.rb

Fixes issue with missing start time in reified object

handle case of new scheduled sessions (2.0.1)

---

app/javascript/mailings/mailing_editor.vue
app/javascript/mailings/mailing_preview.vue

refactor to use not references.

PLAN-729 fix mailing modals (2.1)

---

app/serializers/conclar/session_serializer.rb

Simple update to the streamed tag.

Update streamed tag to use Environment filter (2.0.1)

---

app/controllers/reports/schedule_reports_controller.rb
app/services/change_service.rb

plan-733, plan-735 fixes for pub diffs getting old state of relations… (2.0.1)

---

app/controllers/reports/program_ops_reports_controller.rb
app/javascript/reports/reports_screen.vue
app/policies/reports/program_ops_report_policy.rb
config/routes.rb
lib/tasks/rbac.rake

plan-721 virtual people report (2.0.1)

---

app/javascript/reports/reports_screen.vue

Also change name to Participant Emails for Virtual Sessions

Add description lines to PLAN-721 report

---

app/javascript/reports/reports_screen.vue

Correct the wording describing the report and fix missing line break.

Modify description for virtual report

---

app/controllers/reports/program_ops_reports_controller.rb

PLAN-738 change to include all participants on pub sessions and add is virtual… (2.0.1)

---

app/javascript/reports/reports_screen.vue

Move out of program ops section, leave some space after that section, and put User Privileges at the bottom.

Move User Privileges report

---

app/javascript/reports/reports_screen.vue

Match 2 recent changes: truncated title columns and eliminating people with virtual attendance type

Modify description of Back of Badge report

---

app/controllers/schedule_controller.rb
app/workers/publication_worker.rb

PLAN-745 Get rid of the people snapshot on publish (2.0.2)

---

lib/tasks/chicon.rake

Make sure the rake to create rooms is up to date with latest room names

make seeds in sync with what we have in prod (2.0.2)

---

app/services/publication_service.rb

Fix publish bug with not removing all assignments that should have be… (2.1.1)

---

app/controllers/people_controller.rb
app/controllers/reports/integrations_reports_controller.rb
app/javascript/profile/person_summary.vue
app/javascript/reports/reports_screen.vue
app/policies/person_policy.rb
app/policies/report_policy.rb
app/services/airmeet_api_service.rb
config/routes.rb
lib/tasks/rbac.rake

more airmeet integration, this time with more diffs!

Plan-709 plan-710 plan-753 airmeet

---

app/controllers/published_sessions_controller.rb
app/controllers/reports/integrations_reports_controller.rb
app/javascript/sessions/session_summary.vue
app/policies/published_session_policy.rb
app/services/airmeet_api_service.rb
config/routes.rb
lib/tasks/rbac.rake

very basic. ignores dropped sessions or dropped people

PLAN-765 airmeet session diff

---

app/controllers/reports/program_ops_reports_controller.rb

PLAN-766 Add room and time to table tents

---

app/controllers/reports/integrations_reports_controller.rb
app/services/airmeet_api_service.rb

- clear room cache before diff
- add 'Added People' tab separate from changed people tab

PLAN-767 PLAN-768 airmeet session diff improvements

---

.github/workflows/docker-publish.yml

Attempting to make the arisia branch build to github's registry.

Experimental github arisia build

---

app/javascript/administration/admin_component.vue
app/javascript/people/people_admin_tab.vue

PLAN-775 move registered field to admin tab

---

app/javascript/components/email_addresses_editor.vue
app/javascript/components/sidebar_vue.vue
app/javascript/constants/strings.js
app/javascript/dashboard/dashboard.vue
app/javascript/people/people_sidebar.vue
app/javascript/people/person_tabs.vue
app/javascript/profile/dl_person.vue
app/javascript/profile/person_demographics.vue
app/javascript/profile/person_details.vue
app/javascript/profile/person_draft_schedule.vue
app/javascript/profile/person_live_schedule.vue
app/javascript/profile/person_schedule_display.vue
app/javascript/profile/person_summary.vue

Still missing (have separate tickets
- status picker in header
- availability tab content
Also added some headings and changed the weight of some headings in the profile edit page general tab.

PLAN-644 first pass at better person flyout

---

app/controllers/reports/schedule_reports_controller.rb
app/services/change_service.rb

Fixes changes showing to desc/room/title when the change set for session is  an add and drop

do not show title/desc/room change on a remove (post chicon?)

---

app/controllers/reports/schedule_reports_controller.rb
app/services/change_service.rb

Reverts ChicagoWorldcon/planorama#695
This is not testable given our current level of QA (ie none) for 3.0.0

Revert "do not show title/desc/room change on a remove (post chicon?)"

---

app/javascript/packs/application.js
app/javascript/profile/person_demographics.vue
app/javascript/profile/person_details.vue
app/javascript/profile/person_edit_modal.vue
app/javascript/profile/person_summary.vue
app/javascript/social-media/simple-social.vue

- do not let the user press save on the modal if there are either errors or no changes
- fix validation on social media fields so it reacts to you typing or changing things.

PLAN-795 fix social media validation

---

app/javascript/navbar/bottom-navbar.vue

PLAN-783 change bottom navbar link hover color to white

---

app/models/agreement.rb

Fix for agreement retrieval to take into account the correct "scopes"

PLAN-786 - fix scoping for retreival of agreements to sign

---

app/javascript/constants/strings.js
app/javascript/login/login.vue

PLAN-801 show different text on 401

---

app/javascript/profile/person_details.vue

It was causing some very weird errors with the cursor skipping a bunch.

PLAN-803 take validation off of bio

---

app/javascript/people/people_sidebar.vue
app/javascript/profile/availability_calendar.vue
app/javascript/profile/availability_flyout_tab.vue
app/javascript/sessions/datetime_picker.vue
app/javascript/shared/convention-timezone.mixin.js
app/javascript/store/availability.store.js
app/javascript/store/model.store.js
app/javascript/store/person_exclusion.store.js
app/javascript/store/session_limit.store.js
app/javascript/store/settings.mixin.js
app/javascript/stylesheets/style.scss
app/javascript/utils/utils.js

- can see limits and selected times on flyout
- cannot yet see exclusions, or other notes
- we will need to test the session schedule date time picker too, as there were changes made there

PLAN-791 person availability on flyout

---

app/javascript/configurations/config_editor.vue
app/javascript/configurations/configurations_manager.vue
app/javascript/constants/strings.js

- Add message about refresh after config change
- Allow label overrides in strings.js
- Add an override label for event_virtual

PLAN-800 PLAN-782 event settings fixes

---

app/javascript/app.vue
app/javascript/components/sheet_importer_vue.vue
app/javascript/packs/application.js
app/javascript/store/app.store.js
app/javascript/store/spinner.mixin.js
app/javascript/surveys/view-responses.vue

Also did some refactoring of where we are setting up validation and also the existing whole page spinner that we have.

PLAN-793 spinner on people import

---

app/javascript/people/people_sidebar.vue
app/javascript/profile/person_email_tab.vue

PLAN-796 fix email component name typo

---

app/javascript/venues/room_sets_manager.vue
app/javascript/venues/rooms_manager.vue
app/javascript/venues/venue_manager.vue
app/javascript/venues/venues_manager.vue

- scrolling now happens outside the tabs instead of inside them, which fixes the styling problems (we're not set up to have subnav at this moment)
- styling fixes and padding on the editor parts
fixes #760

PLAN-805 minor room styling fixes

---

app/javascript/constants/strings.js
app/javascript/profile/person_details.vue

PLAN-784 add accommodation fields to profile page

---

app/javascript/navbar/top-navbar.vue

it pointed towards the old repo. now it points towards the new one.

fix about link

---

app/controllers/survey/submissions_controller.rb
app/javascript/store/survey/survey.store.js
app/javascript/surveys/survey_table.vue
db/seeds/development/survey.seeds.rb
db/seeds/test/survey.seeds.rb
lib/tasks/survey.rake
spec/models/survey_spec.rb

Changed spec and other places that were missed when changing anon to unassigned

fixes for anonymous to unassigned

---

app/controllers/home_controller.rb
app/policies/survey/submission_policy.rb
app/policies/survey_policy.rb
config/routes.rb

fixes for redirect for new person and for anon surveys view and submission for a person with no role

Fix survey new person bugs

---

app/controllers/people_controller.rb
app/javascript/login/new_password.vue

login
And fix spelling mistake

Check password needs to be done also without a

---

app/javascript/login/login_password_field.vue
config/routes.rb

Changed the password check to use post (now just as secure as sign in)

Change check password to post request

---

app/javascript/login/account_setup.vue
app/javascript/login/new_password.vue
app/javascript/login/pw_requirements.vue

- Consolidated that text into one place
- Updated the CC BY 4.0 attribution
- Stopped lying to our users as much on the create password description - we aren't checking previous passwords at all

PLAN-828 PLAN-829 PLAN-833 fix password description

---

app/javascript/login/pw_requirements.vue

Add back in "one of your most recent passwords"

PLAN-833 fix password requirements

---

app/javascript/auth/person_session.mixin.js
app/javascript/login/account_setup.vue
app/javascript/navbar/top-navbar.vue

PLAN-840 fix email on account setup screen

---

app/javascript/login/login_password_field.vue

* PLAN-841 fix remote validation by @Gailbear in https://github.com/PlanoramaEvents/planorama/pull/832
**Full Changelog**: https://github.com/PlanoramaEvents/planorama/compare/v3.1.0-rc7...v3.1.0-rc8

v3.1.0-rc8

---

config/brakeman.ignore

This is needed so that the prod build can proceed

Fixes brakeman scan for deploy/main

---

app/javascript/login/login.vue
app/javascript/login/login_password_field.vue

We shouldn't be validating on password entry, only password creation.

PLAN-847 No validation on login password field

---

app/services/identity_service.rb

When person created via OAuth make them a participant

---

app/javascript/surveys/survey_question.vue

I think this is the only one that is missing

Add missing validation for text box

---

app/javascript/surveys/survey-page.vue

Fixes a bug in the assign test for survey to ensure the test is done after the survey load

fix the timing issue for survey loading

---

app/controllers/auth/omniauth_callbacks_controller.rb
app/javascript/login/login.vue
app/javascript/login/login_integrations.vue
app/javascript/profile/person_summary.vue
app/javascript/profile/registration_link.vue
app/javascript/store/login_integrations.mixin.js

Add in redirect for surveys etc when authenticating with Clyde/Oauth
Also Add back in test for person self link for oauth

Add redirect pass through when using oauth

---

app/javascript/integrations/clyde_settings.vue

PLAN-863 cosmetic fixes for settings page

---

app/controllers/people_controller.rb
app/policies/person_policy.rb
config/routes.rb
lib/tasks/rbac.rake

plan-854 Add unlink endpoint

---

config/routes.rb

Fix erroneous period in route file

Fix typo in routes

---

app/javascript/components/plano_modal.vue

Found that plano modal on hide was not calling hide - fixed

Fix the modal exit

---

app/javascript/shared/email_field_veevalidate.vue
app/javascript/surveys/edit-survey-question.vue
app/javascript/surveys/survey-page.vue
app/javascript/surveys/survey_question.vue

This is a bunch of different fixes to use vee-validate instead of the native browser validation.

Fix form validation

---

app/controllers/sessions_controller.rb
app/javascript/people/person_tabs.vue
app/policies/session_policy.rb
config/routes.rb

It will instead say "Coming Soon!" in a centered way.

PLAN-872 Hide contents of session tabs when none are open for interest

---

app/javascript/configurations/config_editor.vue
app/javascript/constants/strings.js
app/javascript/profile/person_demographics.vue
app/javascript/profile/person_details.vue
app/models/parameter_name.rb
lib/tasks/parameters.rake

As per request this is now a single switch - needs a decent string in the strings js to describe what it is doing.
Also the radios on config editor are now "buttons" - request by Anna was to match them a "toggle switch"...

PLAN-871 single switch change

---

app/javascript/administration/admin_component.vue
app/javascript/administration/admin_configurations.vue
app/javascript/app.router.js
app/javascript/navbar/side-navbar.vue

PLAN-873 move editor to new admin page

---

app/javascript/people/person_tabs.vue

PLAN-876 coming soon text format

---

app/javascript/surveys/edit-survey-question.vue

PLAN-861 show required question status in survey editor when not selected

---

db/seeds/development/survey.seeds.rb
db/seeds/test/survey.seeds.rb

For some reason the sort order is needed, so I added it to the test data

Fix the seed data for test surveys

---

app/javascript/profile/person_demographics.vue
app/javascript/profile/person_details.vue

We spelled coming with too many 'm's so this is a quick fix for that.

Fix mis-spelling of coming

---

app/controllers/page_contents_controller.rb
app/javascript/constants/strings.js
app/javascript/page-content/page_content.mixin.js
app/javascript/page-content/page_content_editor.vue

NOTE: primary and secondary buttons are sane color which probably should be changed (custom.css)

Add clear button for clearing custom content

---

app/controllers/surveys_controller.rb

Fixes problem with page speed that was reported

Fix survey table load speed by not loading assigned people as well

---

app/javascript/sessions/session.js
app/javascript/sessions/session_table.vue

Add update and create date to session grid

---

app/javascript/profile/person_details.vue

As discussed with Anna instead of making this the date of chicon make the message generic

Change the text to be generic message

---

app/javascript/page-content/page_content_editor.vue

Because there was a fairly bad bug with it we don't have time to fix

PLAN-879 disable reset button

---

app/javascript/components/model_tags.vue
app/javascript/profile/session_search.vue
app/javascript/sessions/session_edit.vue
app/javascript/store/tags.mixin.js
config/routes.rb
lib/tasks/curated_tags.rake

- change curated tag seed values to lower case (as the tags are)
- fix tags search in participant session selection
- fix values in tag picker
- change display in table with no tags to the empty string
- switch colors of tags and labels

PLAN-898 more tags

---

lib/tasks/rbac.rake

Model name was mis-spelled for RBAC

PLAN-924 Fix spelling mistake of model

---

app/javascript/surveys/survey_question.vue

PLAN-914 add validation message to option questions

---

app/javascript/app.router.js
app/javascript/constants/strings.js
app/javascript/login/login.vue

PLAN-926 log you out if you have no roles

---

app/javascript/sessions/person_details.vue

PLAN-935 Add other demographics to detail flyout as per G24

---

app/javascript/surveys/survey.js
app/serializers/survey_serializer.rb

Since we already had the data in the survey JSON it is a small change

PLAN-936 Add number of submissions to survey grid

---

app/javascript/surveys/manage-survey.vue
app/javascript/surveys/survey.mixin.js
app/javascript/surveys/view-responses.vue

removing condition round fetch paged - may fix Anna's issue

Fix survey select

---

app/javascript/components/pill_display.vue
app/javascript/configurations/configurations_manager.vue
app/javascript/sessions/session_edit.vue
app/javascript/store/area.mixin.js

PLAN-939 make areas like tags

---

app/javascript/app.router.js
app/javascript/surveys/edit-survey-question.vue
app/javascript/surveys/page.mixin.js

Issue was that the code to get the questions titles has null until
the store is loaded. Put in condition to deal with empty questions,
then when we have data let reactive load deal with it.

fix timing issue for questions

---

app/javascript/surveys/survey-page.vue

PLAN-942 it is too late to write useful messages

---

app/javascript/login/login_integrations.vue

disable clyde login

---

app/javascript/profile/person_surveys.vue

PLAN-954 use correct variable to filter

---

app/javascript/people/people_sidebar.vue
app/javascript/people/person_tabs.vue
app/javascript/profile/person_surveys.vue

Plan 964 participants see own surveys

---

app/javascript/components/email_address_editor.vue
app/javascript/components/email_addresses_editor.vue

Anna spacing changes

---

app/javascript/constants/strings.js
app/javascript/profile/registration_link.vue

PLAN-976 Add "What does it mean to link to registration?"

---

app/javascript/profile/availability_calendar.vue

finding component to fix scrolling
This fixes the scroll issue on availability when user picks another timezone

PLAN-990 Make sure dom has finished updating before

---

app/controllers/registration_sync_data_controller.rb
app/models/job_status.rb
app/models/publication_status.rb
app/models/registration_sync_status.rb
app/policies/registration_sync_datum_policy.rb
app/services/clyde_service.rb
app/services/identity_service.rb
app/workers/registration_sync_worker.rb
config/routes.rb
db/migrate/20240602172220_add_status_info_to_job.rb
db/structure.sql
lib/tasks/rbac.rake

Improved the syncing
Also endpoint for the sync stats `registration_sync_data/sync_statistics`

Add status to reg sync

---

app/javascript/profile/dl_person.vue
app/javascript/profile/person_details.vue

PLAN-995 remove reg link and add ticket number view

---

app/controllers/sessions_controller.rb
app/models/session.rb
app/serializers/session_serializer.rb

Reduce load time and memory (not eager loading some of the related data that we really do not need)

Plan 997 speed up session load

---

app/serializers/session_serializer.rb

Quick fix for the serializer when the tags or labels is empty

Need to ensure empty array is used and not nil

---

app/javascript/store/person.store.js

PLAN-998 resolve promise on success

---

app/javascript/people/person-edit-reg-number.vue
app/javascript/shared/spinner-button.vue
app/javascript/store/person.store.js
app/javascript/store/person_sync_datum.mixin.js

replace person and confirmation dialog

---

app/javascript/people/person-edit-reg-number.vue
app/javascript/shared/spinner-button.vue
app/javascript/store/person.store.js
app/javascript/store/person_sync_datum.mixin.js
app/models/person.rb
app/models/person_sync_datum.rb
app/serializers/person_serializer.rb
app/serializers/person_sync_datum_serializer.rb
db/structure.sql
spec/models/person_spec.rb

PLAN-1007 collapse for matched person

---

app/services/session_service.rb

Fixes dupe column error in report - emergency problem reported by G24

PLAN-1009 Remove code that causes dupe table in query

---

app/views/xml_templates/schedule.nokogiri

PLAN-1011 Remove HTML elements in session descriptions

---

app/javascript/constants/strings.js
app/javascript/people/people_admin_tab.vue
app/javascript/people/person-edit-reg-number.vue

PLAN-1001 Bold name in confirmation dialog

---

app/controllers/reports/program_ops_reports_controller.rb
app/controllers/reports/session_reports_controller.rb
app/controllers/sessions_controller.rb
app/javascript/sessions/session.js
app/javascript/sessions/session_sidebar.vue
app/javascript/sessions/session_summary.vue
app/models/person_schedule.rb
app/models/published_session.rb
app/models/session.rb
app/serializers/person_schedule_serializer.rb
app/serializers/published_session_serializer.rb
app/serializers/session_serializer.rb
db/migrate/20240622165823_add_short_title_to_sessions.rb
db/structure.sql
spec/models/session_spec.rb

PLAN-1003 Add short title (max 40 chars) to session

---

app/controllers/concerns/resource_methods.rb
app/models/application_role.rb
app/models/concerns/dirty_associations.rb
app/models/person.rb
app/models/session.rb
app/models/survey.rb
app/models/survey/page.rb
app/models/survey/question.rb

PLAN-1014 ensure that nested attribute changes mark model as dirty/changed for the 200/204 response

---

app/controllers/rce_controller.rb

appear on the RCE schedule !!!!

Need event type and stage/room for room to

---

app/controllers/reports/schedule_reports_controller.rb

As requested by G24 - sessions added put their UUID in the add sheet

Add UUID for sessions added

---

lib/tasks/g24.rake

PLAN-1024 Add Hall 2 as an online stage

---

app/javascript/components/plano_editor.vue

We will need to upgrade to CkEditor 5 and reg for a open source license
Until that is done this will suppress the messages that are starting to appear

PLAN-1025 suppress upgrade message till we upgrade JS libs

---

app/controllers/reports/program_ops_reports_controller.rb

Only use short title if present for the "Truncated Title..." field

PLAN-1015 Keep full title

---

app/controllers/people_controller.rb

Ensure session limits are included in the serialized person

---

app/controllers/sessions_controller.rb
app/models/session.rb
app/serializers/session_serializer.rb

speeds up the session load by at least a factor of 2

PLAN-1040 Adjusting the query for conflict count

---

app/serializers/conclar/session_serializer.rb

as per latest need for discord channel - need room id as well as item id

PLAN-1046 Change the chat URL 

---

app/lib/migration_helpers/plano_views.rb

Small fix so that the materialized view create works with a new db

PLAN-1064 Fix view helper

---

app/controllers/surveys_controller.rb

(not the assigned people as that would
slow things down)

PLAN-1067 Put the updated_by etc people back into the serializer 

---

app/javascript/store/table.mixin.js

PLAN-1069 - fix for default filter query

---

app/javascript/profile/interest_indicator.vue
app/javascript/profile/session_selector.vue

so that paging does not lose data

ensure the assignment list is in sync with changes

---

app/javascript/profile/interest_indicator.vue
app/javascript/profile/session_selector.vue
app/javascript/store/table.mixin.js

Bug fixes for 3.7.7: fixes selections getting lost on paging

v3.7.7-rc2

---

.github/workflows/deploy.yml
.github/workflows/docker-publish.yml

Github changed version of ubuntu for the actions

update the runner as per github doc

---

app/javascript/page-content/page_content_editor.vue

The fetchScheudleWorkflows does not load the page data (just the workflow states).
The fetch_content needed to be called to get the content for the page

ensure the page content is loaded on page load

---

app/controllers/concerns/resource_methods.rb
app/javascript/mailings/mailing_editor.vue
app/javascript/shared/toast-mixin.js
app/javascript/store/model.store.js

PLAN-1072 Tweaks to take into account PATCH that do not

---

script/planorama_sidekiq.sh
script/planorama_start.sh

version of vite clobbers the config and breaks
dev

fix the vite install branch to use yarn this
